\documentclass{article}
\usepackage{amscd, amssymb, amsmath, verbatim, setspace}
\usepackage[left=1.0in, right=1.0in, top=1.0in, bottom=1.0in]{geometry}
\usepackage{mathrsfs}
\usepackage{listings}
<<echo=FALSE>>=
library(knitr)
opts_knit$set(concordance=TRUE)
opts_chunk$set(background="white", highlight=FALSE, fig.keep="high", out.width="0.33\\linewidth")
@
\begin{document}

\begin{flushright}
  Arif Ali\\
  ANLY-511 Prob. Modeling \& Stat. Computing\\
	Oct 29, 2015\\
\end{flushright}

\begin{center}
  \LARGE\textbf{Homework \#6}
\end{center}

\section*{Problem 41}
<<>>=
Z = (51-48)/(9/sqrt(30))
pnorm(Z, lower.tail = F)
@
\section*{Problem 42}
For each Xi ~ U(0,1) the mean is .5 so the mean of Z is 12*.5-6 = 0. For the variance of each Xi, it is 1/12*(1-0) = 1/12. The Variance of Z is 1/12*12 - 0 = 1. Z has the mean and variance of a standard normal distribution. By theorem 4.2, since all X are i.i.d witht the same variances and means, then any constant z will follow the normal distribution.
\section*{Problem 43}
\subsection*{Part A}
<<>>=
#Part A
meanY_X = 7-10
#[1] -3
sdY_X = sqrt(9/sqrt(9)+25/sqrt(12))
#[1] 3.196385
@
\subsection*{Part B}
<<>>=
simX_Y = function(i){
  X = rnorm(9, mean = 7, sd = 3)
  Y = rnorm(12, mean = 10, sd = 5)
  meanY_X = mean(X) - mean(Y)
  sdY_X = sqrt((sd(X))^2/sqrt(length(X))+(sd(Y))^2/sqrt(length(Y)))
  return(list(meanY_X, sdY_X))
}
Problem43B = sapply(1:10000, simX_Y)

Problem43B = as.data.frame(t(Problem43B))
par(mfrow = c(1,2))
hist(unlist(Problem43B$V1), breaks = 25)
abline(v = meanY_X, col = "red", lwd = 2)
mean(unlist(Problem43B$V1))
hist(unlist(Problem43B$V2), breaks = 25)
abline(v = sdY_X, col = "red", lwd = 2)
mean(unlist(Problem43B$V2))
@
Based on the histogram and the means of the simulationed SE and mean, both seem close to the theoretical ones.
\section*{Problem 44}
\subsection*{Part A}
<<>>=
X20 = replicate(1000, sum(rexp(20, rate = 2)))
hist(X20, probability = T, breaks = 25)
@
\subsection*{Part B}
<<>>=
mean(X20)
var(X20)
@
\subsection*{Part C}
<<>>=
mean(X20<=10)
@
\section*{Problem 45}
<<>>=
par(mfrow = c(1,2))
my.vars = sapply(rep(20, times = 1000), function(x){var(rnorm(x, 25, 7))})
mean(my.vars)
var(my.vars)
hist(my.vars, breaks = 25)
#dev.new()
qqnorm(my.vars)
qqline(my.vars)
@
At n = 20, the qqnorm plot does not follow the the qqline; therefore, it does not appear to be normally distributed. The Histogram is skrewed
<<>>=
par(mfrow = c(1,2))
my.vars = sapply(rep(50, times = 1000), function(x){var(rnorm(x, 25, 7))})
mean(my.vars)
var(my.vars)
hist(my.vars, breaks = 25)
#dev.new()
qqnorm(my.vars)
qqline(my.vars)
@
At n = 50, the qqnorm plot follows the qqline close than at n = 20, but it still deviates a significant amount of the time so, it does not appear to be normally distributed. The histogram has two peaks.
<<>>=
par(mfrow = c(1,2))
my.vars = sapply(rep(200, times = 1000), function(x){var(rnorm(x, 25, 7))})
mean(my.vars)
var(my.vars)
hist(my.vars, breaks = 25)
#dev.new()
qqnorm(my.vars)
qqline(my.vars)
@
At n = 200, it closely follows the line so it is normally distributed. The histogram is a rough, but looks somewaht bell shaped.
\section*{Problem 46}
<<>>=
pop = c(3,6,7,9,11,14)
Problem46 = combn(pop, m = 3, FUN = min)
mean(Problem46)
hist(Problem46)
@
It looks like we are trying to estimate the min of the population. That seems to be the parameter we are trying to find.
\section*{Problem 47}
\subsection*{Part A}
\begin{equation*}
E(X)=10
\end{equation*}
\subsection*{Part B}
<<>>=
my.means = replicate(1000, mean(rexp(30, rate = 1/10)))
mean(my.means>=12)
@
\subsection*{Part C}
The proportion doesn't seem too small, so it doesn't seem to be unusual.
\section*{Problem 48}
\subsection*{Part A}
\begin{equation*}
f_{min}(x)=n(1-(1-e^{-\lambda x}))^{n-1}*\lambda e^{-\lambda x}=n*e^{(n-1)-\lambda x}*\lambda^{-\lambda x}=n\lambda e^{-n\lambda}
\end{equation*} 
\begin{equation*}
\therefore X_{min}\sim Exp(n\lambda)
\end{equation*}
\subsection*{Part B}
<<>>=
Problem48B = replicate(1000, min(rexp(25, rate = 7)))
1/(25*7) - mean(Problem48B)
@
\end{document}